version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://merntd:merntd@cluster0.tqaeshh.mongodb.net/merntd?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
